// GENERATED FILE — do not edit by hand.
// Generated by tools/gen_unicode_tables.py from Unicode 15.1.0.
#ifndef OPENRAR_UNICODE_TABLES_HPP
#define OPENRAR_UNICODE_TABLES_HPP

#include "../../src/core/types.hpp"

#include <string>

namespace openrar::unicode {

inline constexpr const char* kUnicodeVersion = "15.1.0";

// Raw table accessors (defined in unicode_tables.cpp).
const core::uint32* case_fold_table(int& count);       // (cp, folded) pairs
const core::uint32* decomposition_table(int& count);   // (cp, a, b) triples, b==0 singleton
const core::uint32* composition_table(int& count);     // (a, b, composite) triples
const core::uint32* combining_class_table(int& count); // (cp, ccc) pairs

// Simple case folding (CaseFolding.txt status C+S).
std::string simple_case_fold(const std::string& utf8);

// NFC canonical composition. Invalid UTF-8 bytes pass through untouched
// (they cannot make two distinct names compare equal).
std::string nfc(const std::string& utf8);

} // namespace openrar::unicode

#endif // OPENRAR_UNICODE_TABLES_HPP
